In [1]:
import numpy as np

**1.Array Creation**
- Create a 1D array of numbers from 10 to 50.
- Create a 3x3 array of random numbers between 0 and 1.


In [2]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [9]:
arr=np.random.random((3,3))
arr

array([[0.48103762, 0.06568316, 0.83109135],
       [0.76171922, 0.82728427, 0.87231289],
       [0.1449603 , 0.17526698, 0.70254325]])

**2.Array  Attributes**	
- Find the shape, size, and data type of the array you created in the previous task.


In [6]:
arr.shape

(3, 3)

In [7]:
arr.size

9

In [8]:
arr.dtype

dtype('float64')

**3.Basic Operations**
- Add 5 to every element of a 1D array.
- Multiply two 2D arrays element-wise.


In [10]:
a=np.array([1,2,3])
a+5

array([6, 7, 8])

In [12]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
a*b

array([[ 5, 12],
       [21, 32]])

**4.Indexing and Slicing**
- Create a 5x5 array of integers from 1 to 25. Extract:
- The first row.
- The last column.
- A subarray of the first three rows and first two columns.


In [13]:
arr=np.random.randint(1,25,size=(5,5))
arr

array([[19,  9, 17, 19,  7],
       [ 3, 15, 16, 18,  2],
       [21, 15, 22, 15, 10],
       [23, 16, 22, 13, 22],
       [11,  6, 16,  3, 18]], dtype=int32)

In [14]:
arr[0]

array([19,  9, 17, 19,  7], dtype=int32)

In [15]:
arr[-1]

array([11,  6, 16,  3, 18], dtype=int32)

In [18]:
arr[:3,:2]

array([[19,  9],
       [ 3, 15],
       [21, 15]], dtype=int32)

**5.Aggregation**
- Create a 10-element array of random integers between 1 and 100. Find:
- The maximum value.
- The minimum value.
- The mean and standard deviation.


In [19]:
arr=np.random.randint(1,100,size=(10,))
arr

array([ 4, 16, 75, 55, 79,  4, 77, 80, 85, 28], dtype=int32)

In [23]:
print(arr.max())

85


In [22]:
print(arr.min())

4


In [24]:
print(arr.mean())
print(arr.std())

50.3
31.962634434601913


**6.	Reshaping**
- Convert a 1D array of numbers from 1 to 12 into a 3x4 matrix.


In [26]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr.reshape((3,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

**7.	Broadcasting**
- Create a 3x3 matrix of ones. Add a 1D array [1, 2, 3] to each row.


In [28]:
ones=np.ones((3,3))
ones+[1,2,3]


array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

**8.	Filtering**
- Create a 1D array of random integers between 1 and 50. Extract all elements that are divisible by 5.


In [32]:
arr=np.random.randint(1,50,size=(3,3))
arr

array([[41,  2, 19],
       [ 2,  9, 20],
       [ 3, 31, 20]], dtype=int32)

In [36]:
arr[arr%5==0]

array([20, 20], dtype=int32)

**9.	Matrix Multiplication**
- Create two 2x2 matrices and perform matrix multiplication.


In [38]:
a=np.array([[1,2],[4,5]])
b=np.array([[6,5],[3,2]])
np.dot(a,b)

array([[12,  9],
       [39, 30]])

**10.	Advanced Indexing**
- Given a 4x4 array, use fancy indexing to extract the diagonal elements.


In [39]:
arr=np.random.randint(1,100,size=(4,4))
arr

array([[10, 39, 51, 18],
       [55, 23, 51, 67],
       [ 5, 21, 12, 31],
       [54, 65, 65, 80]], dtype=int32)

In [40]:
arr.diagonal()

array([10, 23, 12, 80], dtype=int32)